# Generated by Django 5.1.2 on 2024-10-21 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("pos", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inbound",
            name="material_inbound_report",
            field=models.ManyToManyField(
                related_name="inbound_reports", to="sales.materialorderreport"
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="responsible_staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialinbound",
            name="inbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_inbounds",
                to="pos.inbound",
            ),
        ),
        migrations.AddField(
            model_name="materialinbound",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.stock"
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="material_inbound",
            field=models.ManyToManyField(
                related_name="inbound",
                through="pos.MaterialInbound",
                to="inventory.stock",
            ),
        ),
        migrations.AddField(
            model_name="materialoutbound",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.stock"
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="material_outbound",
            field=models.ManyToManyField(
                related_name="outbound",
                through="pos.MaterialOutbound",
                to="inventory.stock",
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="material_outbound_report",
            field=models.ManyToManyField(
                related_name="outbound_reports", to="sales.materialorderreport"
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="order_requisition_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.orderrequisition",
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="responsible_staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialoutbound",
            name="outbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_outbounds",
                to="pos.outbound",
            ),
        ),
    ]
