# Generated by Django 5.1.2 on 2024-10-22 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("expiration_date", models.DateField(null=True)),
                ("date_added", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OutboundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.FloatField()),
                ("sold_date", models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="materialinbound",
            name="inbound",
        ),
        migrations.RemoveField(
            model_name="materialinbound",
            name="material",
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="material_inbound",
        ),
        migrations.RemoveField(
            model_name="materialoutbound",
            name="material",
        ),
        migrations.RemoveField(
            model_name="materialoutbound",
            name="outbound",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="material_outbound",
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="exp_date",
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="material_inbound_report",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="material_outbound_report",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="order_requisition_number",
        ),
        migrations.AddField(
            model_name="inbound",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inbound",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="inbound",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="outbound",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="outbound",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="outbound",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
