# Generated by Django 5.1.2 on 2024-10-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_category_date_added_category_date_updated_and_more"),
        ("pos", "0003_inbounditem_outbounditem_and_more"),
        ("sales", "0002_remove_materialorderreport_inbound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outbound",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="outbound",
            name="tax",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="outbound",
            name="tax_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="outbound",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="inbounditem",
            name="inbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_items",
                to="pos.inbound",
            ),
        ),
        migrations.AddField(
            model_name="inbounditem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.stock"
            ),
        ),
        migrations.AddField(
            model_name="outbounditem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.stock"
            ),
        ),
        migrations.AddField(
            model_name="outbounditem",
            name="outbound",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbounds_items",
                to="pos.outbound",
            ),
        ),
        migrations.DeleteModel(
            name="MaterialInbound",
        ),
        migrations.DeleteModel(
            name="MaterialOutbound",
        ),
    ]
