# Generated by Django 5.1.2 on 2024-10-28 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0005_rename_item_inbounditem_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbound",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="inbounditem",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
