# Generated by Django 5.1.2 on 2024-10-29 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pos", "0006_remove_inbound_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outbound",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="outbound",
            name="total_price",
        ),
    ]
