# Generated by Django 5.1.2 on 2024-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_category_date_added_category_date_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="status",
        ),
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
