# Generated by Django 5.1.2 on 2024-10-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_category_status_category_active_stock_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rgb", models.CharField(max_length=7)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="inventory.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Color",
                "verbose_name_plural": "Product Colors",
                "unique_together": {("product", "rgb")},
            },
        ),
    ]
