# Generated by Django 5.1.2 on 2024-10-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_remove_materialorderreport_inbound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="code",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
