# Generated by Django 5.1.2 on 2024-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_sale_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="tendered_amount",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
