# Generated by Django 5.1.2 on 2024-10-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_alter_sale_tendered_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="amount_change",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
