# Generated by Django 5.1.2 on 2024-10-28 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_category_status_category_active_stock_active"),
        ("pos", "0006_remove_inbound_date_created_and_more"),
        ("sales", "0005_alter_sale_amount_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("expiration_date", models.DateField(null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                (
                    "inbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_reports",
                        to="pos.inbound",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.stock",
                    ),
                ),
            ],
        ),
    ]
