# Generated by Django 5.1.2 on 2024-10-29 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_materialreport_outbound_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialreport",
            name="outbound",
        ),
    ]
